name: dieta_diaria
description: "Dieta Diária é um aplicativo mobile para organizar e acompanhar suas dietas."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  rename: ^3.0.2
  intl: ^0.19.0
  phosphor_flutter: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app/logo_green_w_bg.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/app/logo_green_w_bg.png
    - assets/images/app/logo_green_w_text.png
    - assets/images/app/logo_grey.png
    - assets/images/app/logo_red.png
    - assets/images/app/logo_white_w_text.png
    - assets/images/app/logo_white.png
